global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9093']

  - job_name: 'jmx_exporter'
    static_configs:
      - targets: ['host.docker.internal:9308']
