version: "3.2"

services:
    keycloak:
        image: quay.io/keycloak/keycloak:18.0.1
        # depends_on:
        #     - mssql
        #     - mssqlscripts
        ports:
            - "8080:8080"
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            # - DB_VENDOR=mssql
            # - DB_USER=sa
            # - DB_PASSWORD=Admin789
            # - DB_ADDR=mssql
            # - DB_DATABASE=Keycloak