version: "3.0"
services:

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=3
      - CONFLUENT_SUPPORT_METRICS_ENABLE=0
    ports:
      - "9092:9092"

  # camunda-platform:
  #   image: camunda/camunda-bpm-platform:latest
  #   hostname: platform
  #   ports:
  #     - "8084:8080"
  #   environment:
  #     DB_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #     DB_URL: dbc:sqlserver://sql_server-db:1433;database=camunda
  #     DB_PASSWORD: Admin789
  #     DB_VALIDATE_ON_BORROW: 'true'
  #     DB_VALIDATION_QUERY: SELECT 1
  #   depends_on:
  #     - sql_server-db

  # sql_server-db:
  #   image: "mcr.microsoft.com/mssql/server"
  #   ports:
  #     - '1435:1433'
  #   environment:
  #     SA_PASSWORD: "Admin789"
  #     ACCEPT_EULA: "Y"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.100.1.1/24
