version: "3.9"
services:
    DB-HML:
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - '1434:1433'
        environment:
            SA_PASSWORD: "Admin789"
            ACCEPT_EULA: "Y"
    DB-PRD:
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - '1435:1433'
        environment:
            SA_PASSWORD: "Admin789"
            ACCEPT_EULA: "Y"
