version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - '1434:1433'
        environment:
            SA_PASSWORD: "Admin789"
            ACCEPT_EULA: "Y"
