version: "3.0"
services:

  # zookeeper:
  #   container_name: zookeeper
  #   image: debezium/zookeeper:1.5
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     - ZOOKEEPER_CLIENT_PORT=2181
  #     - ZOOKEEPER_TICK_TIME=2000

  # kafka:
  #   container_name: kafka
  #   image: debezium/kafka:1.5
  #   ports:
  #     - "9092:9092"
  #   links:
  #     - "zookeeper:zookeeper"
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  #     - KAFKA_NUM_PARTITIONS=3
  #     - CONFLUENT_SUPPORT_METRICS_ENABLE=0
  #   depends_on:
  #     - zookeeper

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=3
      - CONFLUENT_SUPPORT_METRICS_ENABLE=0
    ports:
      - "9092:9092"

  # mysql:
  #   container_name: mysql
  #   image: "debezium/example-mysql:1.5"
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=debezium 
  #     - MYSQL_USER=mysqluser
  #     - MYSQL_PASSWORD=mysqlpw

  connect:
    container_name: connect
    image: "debezium/connect:1.5"
    ports:
      - '8083:8083'
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    links:
      - "zookeeper:zookeeper"
      - "kafka:kafka"
      # - "mysql:mysql"
    depends_on:
      - zookeeper
      - kafka
      # - mysql

# networks:
#   default:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#       - subnet: 10.100.1.1/24
