version: "3.0"
services:

  # zookeeper:
  #   container_name: zookeeper
  #   image: debezium/zookeeper:1.5
  #   ports:
  #     - "2181:2181"
  #     # - "2888:2888"
  #     # - "3888:3888"

  kafka:
    container_name: kafka
    image: debezium/kafka:1.5
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
    # depends_on:
    #   - zookeeper

  mysql:
    container_name: mysql
    image: "debezium/example-mysql:1.5"
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=debezium 
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  connect:
    container_name: connect
    image: "debezium/connect:1.5"
    ports:
      - '8083:8083'
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      # - zookeeper
      - kafka
      - mysql

# networks:
#   default:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#       - subnet: 10.100.1.1/24
