version: "3.0"
services:

  camunda-platform:
    image: camunda/camunda-bpm-platform:tomcat-latest
    container_name: camunda-bpm
    hostname: platform
    ports:
      - "8084:8080"
    environment:
      # DB_DRIVER: com.microsoft.sqlserver.jdbc.SQLServerDriverc
      # DB_URL: jdbc:sqlserver://sql-server-db:1433;database=master
      # DB_USERNAME: sa
      # DB_PASSWORD: Admin789
      # DB_VALIDATION_QUERY: "SELECT 1"
      DB_DRIVER: com.mysql.jdbc.Driver
      DB_URL: jdbc:mysql://mysql-db:3306/camunda_db?autoReconnect=true
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_VALIDATION_QUERY: "SELECT 1"
    # volumes:
    #   - ~/camunda/mssql-jdbc-7.4.1.jre11.jar:/camunda/lib/mssql-jdbc-7.4.1.jre11.jar
    depends_on:
      - mysql-db
      # - sql-server-db

  sql-server-db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: camunda_sqlserver
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Admin789"
      ACCEPT_EULA: "Y"

  mysql-db:
    image: mysql:latest
    container_name: camunda_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: camunda_db 
